In [138]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score, f1_score, classification_report

In [139]:
trainingData = pd.read_csv('Combined_Intensities_Multilabel.csv')

spectra = trainingData.iloc[:, :-2]
labels = trainingData.iloc[:, -2:]

In [140]:
rf = RandomForestClassifier(n_estimators= 100, random_state=1)
model = MultiOutputClassifier(rf)
model.fit(spectra,labels)


MultiOutputClassifier(estimator=RandomForestClassifier(random_state=1))

In [141]:
Fifty_Fifty_Data =pd.read_csv('50_Staph_50_PAO_Intensities.csv') #This sample contained a 1:1 ratio of S.aureus and P. aeruginosa

spectra_50_50 = Fifty_Fifty_Data.iloc[:, :-2]
labels_50_50 = Fifty_Fifty_Data.iloc[:, -2:]

predicted_probabilities_50_50 = model.predict_proba(spectra_50_50)
predicted_probabilities_50_50

[array([[0.09, 0.91],
        [0.09, 0.91],
        [0.38, 0.62],
        [0.45, 0.55],
        [0.3 , 0.7 ],
        [0.67, 0.33],
        [0.3 , 0.7 ],
        [0.52, 0.48],
        [0.75, 0.25],
        [0.02, 0.98],
        [0.  , 1.  ],
        [0.02, 0.98],
        [0.22, 0.78],
        [0.37, 0.63],
        [0.3 , 0.7 ],
        [0.13, 0.87],
        [0.03, 0.97],
        [0.33, 0.67],
        [0.64, 0.36],
        [0.64, 0.36],
        [0.73, 0.27],
        [0.72, 0.28],
        [0.83, 0.17],
        [0.82, 0.18],
        [0.47, 0.53],
        [0.42, 0.58],
        [0.74, 0.26],
        [0.03, 0.97],
        [0.03, 0.97],
        [0.03, 0.97],
        [0.37, 0.63],
        [0.29, 0.71],
        [0.25, 0.75],
        [0.18, 0.82],
        [0.01, 0.99],
        [0.67, 0.33]]),
 array([[0.91, 0.09],
        [0.91, 0.09],
        [0.62, 0.38],
        [0.55, 0.45],
        [0.7 , 0.3 ],
        [0.33, 0.67],
        [0.7 , 0.3 ],
        [0.48, 0.52],
        [0.25, 0.75],
        

In [142]:
prediction = model.predict(spectra_50_50) #With default threshold value = 0.5
print(recall_score(labels_50_50, prediction, average= None))
print(accuracy_score(labels_50_50, prediction))
#Notice with default threshold value, it never predicts a 50/50 probability therefore model never predicts "precense" of both bacteria 

[0.69444444 0.30555556]
0.0


In [143]:
threshold = 0.30 #Custom threhsold --> if probability >=0.3 then we assume presence of bacteria

predicted_labels_custom = (predicted_probabilities_50_50[0][:, 1] >= threshold).astype(int), (predicted_probabilities_50_50[1][:, 1] >= threshold).astype(int)

predicted_labels_custom = np.column_stack(predicted_labels_custom)

predicted_labels_custom

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1]])

In [144]:
accuracy_custom = accuracy_score(labels_50_50, predicted_labels_custom)
accuracy_custom

0.4166666666666667

In [145]:
print(recall_score(labels_50_50, predicted_labels_custom, average= None)) 

[0.83333333 0.58333333]


In [151]:
ten_ninety_Data =pd.read_csv('10_Staph_90_PAO_Intensities.csv') #This sample contained a 10% to 90%  ratio of S.aureus and P. aeruginosa

spectra_10_90 = ten_ninety_Data.iloc[:, :-2]
labels_10_90 = ten_ninety_Data.iloc[:, -2:]

predicted_probabilities_10_90 = model.predict_proba(spectra_10_90)

threshold = 0.30 #Custom threhsold --> if probability >=0.3 then we assume presence of bacteria

predicted_labels_custom = (predicted_probabilities_10_90[0][:, 1] >= threshold).astype(int), (predicted_probabilities_10_90[1][:, 1] >= threshold).astype(int)

predicted_labels_custom = np.column_stack(predicted_labels_custom)

print(accuracy_score(labels_10_90,predicted_labels_custom))
print(recall_score(labels_10_90,predicted_labels_custom, average = None))

predicted_labels_custom

0.027777777777777776
[1.         0.02777778]


array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0]])

In [154]:
thirty_seventy_Data =pd.read_csv('30_Staph_70_PAO_Intensities.csv') #This sample contained a 30% to 70%  ratio of S.aureus and P. aeruginosa

spectra_30_70 = thirty_seventy_Data.iloc[:, :-2]
labels_30_70 = thirty_seventy_Data.iloc[:, -2:]

predicted_probabilities_30_70 = model.predict_proba(spectra_30_70)

threshold = 0.30 #Custom threhsold --> if probability >=0.3 then we assume presence of bacteria

predicted_labels_custom = (predicted_probabilities_30_70[0][:, 1] >= threshold).astype(int), (predicted_probabilities_30_70[1][:, 1] >= threshold).astype(int)

predicted_labels_custom = np.column_stack(predicted_labels_custom)

print(accuracy_score(labels_30_70,predicted_labels_custom))
print(recall_score(labels_30_70,predicted_labels_custom, average = None))

predicted_labels_custom

0.08333333333333333
[1.         0.08333333]


array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1]])

In [155]:
seventy_thirty_Data =pd.read_csv('70_Staph_30_PAO_Intensities.csv') #This sample contained a 70% to 30%  ratio of S.aureus and P. aeruginosa

spectra_70_30 = seventy_thirty_Data.iloc[:, :-2]
labels_70_30 = seventy_thirty_Data.iloc[:, -2:]

predicted_probabilities_70_30 = model.predict_proba(spectra_70_30)

threshold = 0.30 #Custom threhsold --> if probability >=0.3 then we assume presence of bacteria

predicted_labels_custom = (predicted_probabilities_70_30[0][:, 1] >= threshold).astype(int), (predicted_probabilities_70_30[1][:, 1] >= threshold).astype(int)

predicted_labels_custom = np.column_stack(predicted_labels_custom)

print(accuracy_score(labels_70_30,predicted_labels_custom))
print(recall_score(labels_70_30,predicted_labels_custom, average = None))

predicted_labels_custom

0.3333333333333333
[0.77777778 0.55555556]


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1]])

In [156]:
ninety_ten_Data =pd.read_csv('90_Staph_10_PAO_Intensities.csv') #This sample contained a 90% to 10%  ratio of S.aureus and P. aeruginosa

spectra_90_10 = ninety_ten_Data.iloc[:, :-2]
labels_90_10 = ninety_ten_Data.iloc[:, -2:]

predicted_probabilities_90_10 = model.predict_proba(spectra_90_10)

threshold = 0.30 #Custom threhsold --> if probability >=0.3 then we assume presence of bacteria

predicted_labels_custom = (predicted_probabilities_90_10[0][:, 1] >= threshold).astype(int), (predicted_probabilities_90_10[1][:, 1] >= threshold).astype(int)

predicted_labels_custom = np.column_stack(predicted_labels_custom)

print(accuracy_score(labels_90_10,predicted_labels_custom))
print(recall_score(labels_90_10,predicted_labels_custom, average = None))

predicted_labels_custom

0.2777777777777778
[0.36111111 0.91666667]


array([[1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 1]])